# Generated by Django 4.2.13 on 2024-07-15 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Callback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "qualification",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("ctcheckbox", models.BooleanField(default=False)),
                ("mricheckbox", models.BooleanField(default=False)),
                ("xraycheckbox", models.BooleanField(default=False)),
                ("mammographycheckbox", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "password",
                    models.CharField(
                        blank=True, default=None, max_length=15, null=True
                    ),
                ),
                (
                    "cnfpassword",
                    models.CharField(
                        blank=True, default=None, max_length=15, null=True
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("contact_no", models.CharField(max_length=15)),
                ("resume", models.FileField(upload_to="uploads/")),
                ("photo", models.ImageField(upload_to="uploads/")),
                ("experience_years", models.PositiveIntegerField()),
                (
                    "stage1status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under_progress", "Under Progress"),
                            ("verified_by_coordinator", "Verified by Coordinator"),
                            ("verification_failed", "Verification Failed"),
                        ],
                        default="applied",
                        max_length=23,
                    ),
                ),
                (
                    "stage2status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under_progress", "Under Progress"),
                            (
                                "verified_by_supercoordinator",
                                "Verified by Supercoordinator",
                            ),
                            ("verification_failed", "Verification Failed"),
                        ],
                        default="applied",
                        max_length=28,
                    ),
                ),
                (
                    "coordinator_message",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "supercoordinator_message",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_quantity", models.IntegerField()),
                ("max_quantity", models.IntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="services.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportingAreaDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mriopt", models.CharField(max_length=50)),
                ("mriothers", models.CharField(max_length=100)),
                ("ctopt", models.CharField(max_length=50)),
                ("ctothers", models.CharField(max_length=100)),
                ("xray", models.BooleanField()),
                ("others", models.BooleanField()),
                (
                    "otherText",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "personal_information",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.personalinformation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RateList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mri1", models.IntegerField(blank=True, default=200, null=True)),
                ("mri2", models.IntegerField(blank=True, default=100, null=True)),
                ("mri3", models.IntegerField(blank=True, default=250, null=True)),
                ("mri4", models.IntegerField(blank=True, default=250, null=True)),
                ("mri5", models.IntegerField(blank=True, default=300, null=True)),
                ("mri6", models.IntegerField(blank=True, default=300, null=True)),
                ("ct1", models.IntegerField(blank=True, default=150, null=True)),
                ("ct2", models.IntegerField(blank=True, default=150, null=True)),
                ("ct3", models.IntegerField(blank=True, default=150, null=True)),
                ("ct4", models.IntegerField(blank=True, default=200, null=True)),
                ("ct5", models.IntegerField(blank=True, default=225, null=True)),
                ("ct6", models.IntegerField(blank=True, default=200, null=True)),
                ("ct7", models.IntegerField(blank=True, default=500, null=True)),
                ("xray1", models.IntegerField(blank=True, default=20, null=True)),
                ("xray2", models.IntegerField(blank=True, default=75, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="No Status Yet", max_length=50
                    ),
                ),
                (
                    "radiologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.personalinformation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=100)),
                ("organization", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=254, verbose_name="Customer Name"),
                ),
                ("amount", models.FloatField(verbose_name="Amount")),
                (
                    "status",
                    models.CharField(
                        default="Pending", max_length=254, verbose_name="Payment Status"
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(max_length=40, verbose_name="Order ID"),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=36, verbose_name="Payment ID"),
                ),
                (
                    "signature_id",
                    models.CharField(max_length=128, verbose_name="Signature ID"),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exinstitution1",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                ("exstdate1", models.DateField(blank=True, default=None, null=True)),
                ("exenddate1", models.DateField(blank=True, default=None, null=True)),
                (
                    "exinstitution2",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                ("exstdate2", models.DateField(blank=True, default=None, null=True)),
                ("exenddate2", models.DateField(blank=True, default=None, null=True)),
                (
                    "exinstitution3",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                ("exstdate3", models.DateField(blank=True, default=None, null=True)),
                ("exenddate3", models.DateField(blank=True, default=None, null=True)),
                (
                    "personal_information",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.personalinformation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenthname", models.CharField(max_length=30)),
                ("tenthgrade", models.CharField(max_length=10)),
                ("tenthpsyr", models.DateField()),
                ("tenthcertificate", models.FileField(upload_to="uploads/")),
                ("twelthname", models.CharField(max_length=30)),
                ("twelthgrade", models.CharField(max_length=10)),
                ("twelthpsyr", models.DateField()),
                ("twelthcertificate", models.FileField(upload_to="uploads/")),
                ("mbbsinstitution", models.CharField(max_length=25)),
                ("mbbsgrade", models.CharField(max_length=10)),
                ("mbbspsyr", models.DateField()),
                ("mbbsmarksheet", models.FileField(upload_to="uploads/")),
                ("mbbsdegree", models.FileField(upload_to="uploads/")),
                ("mdinstitution", models.CharField(max_length=25)),
                ("mdgrade", models.CharField(max_length=10)),
                ("mdpsyr", models.DateField()),
                ("mdmarksheet", models.FileField(upload_to="uploads/")),
                ("mddegree", models.FileField(upload_to="uploads/")),
                ("videofile", models.FileField(upload_to="uploads/")),
                (
                    "personal_information",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.personalinformation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promo_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("casecount", models.PositiveIntegerField(default=0)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "service",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accholdername", models.CharField(max_length=25)),
                ("bankname", models.CharField(max_length=25)),
                ("branchname", models.CharField(max_length=25)),
                ("acnumber", models.CharField(max_length=15)),
                ("ifsc", models.CharField(max_length=15)),
                ("pancardno", models.CharField(max_length=10)),
                ("aadharcardno", models.CharField(max_length=12)),
                ("pancard", models.FileField(upload_to="uploads/")),
                ("aadharcard", models.FileField(upload_to="uploads/")),
                ("cheque", models.FileField(upload_to="uploads/")),
                (
                    "personal_information",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.personalinformation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvailabilityDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monday", models.BooleanField()),
                ("tuesday", models.BooleanField()),
                ("wednesday", models.BooleanField()),
                ("thursday", models.BooleanField()),
                ("friday", models.BooleanField()),
                ("saturday", models.BooleanField()),
                ("sunday", models.BooleanField()),
                (
                    "starttime1",
                    models.CharField(
                        blank=True, default="Individual", max_length=100, null=True
                    ),
                ),
                (
                    "endtime1",
                    models.CharField(
                        blank=True, default="Individual", max_length=100, null=True
                    ),
                ),
                (
                    "starttime2",
                    models.CharField(
                        blank=True, default="Individual", max_length=100, null=True
                    ),
                ),
                (
                    "endtime2",
                    models.CharField(
                        blank=True, default="Individual", max_length=100, null=True
                    ),
                ),
                (
                    "starttime3",
                    models.CharField(
                        blank=True, default="Individual", max_length=100, null=True
                    ),
                ),
                (
                    "endtime3",
                    models.CharField(
                        blank=True, default="Individual", max_length=100, null=True
                    ),
                ),
                (
                    "starttime4",
                    models.CharField(
                        blank=True, default="Individual", max_length=100, null=True
                    ),
                ),
                (
                    "endtime4",
                    models.CharField(
                        blank=True, default="Individual", max_length=100, null=True
                    ),
                ),
                (
                    "personal_information",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.personalinformation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AchievementDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "award1",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                ("awarddate1", models.DateField(blank=True, default=None, null=True)),
                (
                    "award2",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                ("awarddate2", models.DateField(blank=True, default=None, null=True)),
                (
                    "publishlink",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "personal_information",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.personalinformation",
                    ),
                ),
            ],
        ),
    ]
