# Generated by Django 4.2.13 on 2024-07-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="educationaldetails", name="mbbsmarksheet",),
        migrations.RemoveField(model_name="educationaldetails", name="mdmarksheet",),
        migrations.CreateModel(
            name="MDMarksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "educational_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mdmarksheets",
                        to="services.educationaldetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MBBSMarksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "educational_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mbbsmarksheets",
                        to="services.educationaldetails",
                    ),
                ),
            ],
        ),
    ]
