# Generated by Django 4.2.13 on 2024-07-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_remove_educationaldetails_mbbsmarksheet_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="mdmarksheet", name="educational_details",),
        migrations.AddField(
            model_name="educationaldetails",
            name="mbbsmarksheet",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="uploads/"
            ),
        ),
        migrations.AddField(
            model_name="educationaldetails",
            name="mdmarksheet",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="uploads/"
            ),
        ),
        migrations.DeleteModel(name="MBBSMarksheet",),
        migrations.DeleteModel(name="MDMarksheet",),
    ]
