# Generated by Django 4.2.14 on 2024-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_remove_mdmarksheet_educational_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinformation",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
