# Generated by Django 4.2.14 on 2024-07-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_personalinformation_email_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="coordinator_message",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="supercoordinator_message",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
