# Generated by Django 4.2.14 on 2024-07-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_personalinformation_coordinator_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementdetails",
            name="award3",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="achievementdetails",
            name="award4",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="achievementdetails",
            name="award5",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="achievementdetails",
            name="awarddate3",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="achievementdetails",
            name="awarddate4",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="achievementdetails",
            name="awarddate5",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="experiencedetails",
            name="exenddate4",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="experiencedetails",
            name="exenddate5",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="experiencedetails",
            name="exinstitution4",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="experiencedetails",
            name="exinstitution5",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="experiencedetails",
            name="exstdate4",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="experiencedetails",
            name="exstdate5",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
