# Generated by Django 4.2.14 on 2024-08-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_remove_uploadfile_cart_uploadfile_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationaldetails",
            name="regfile",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="uploads/"
            ),
        ),
        migrations.AddField(
            model_name="educationaldetails",
            name="regno",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
