# Generated by Django 4.2.14 on 2024-08-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_educationaldetails_regfile_educationaldetails_regno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationaldetails",
            name="regfile",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
    ]
